### PR TITLE
Check arguments before attempting to use them

### LINKED ISSUE #412: Check arguments before doing stuff
While looking at #268 it seems that we almost never throw `Argument[Null|OutOfRange]Exception` if a consumer passes invalid inputs (e.g. null SteamID).

We should add null checks and range checks to our public API surface.

### PR DESCRIPTION
**Pull request by yaakov-h**
There are a lot of places in SK2 where we can be passed null values and either attempt to operate on them immediately, or store them and fail at a later time.

This PR adds null argument checking to the API surface, so that consumer misuse is exposed immediately at the original call-site, with an explanation of what is wrong.

PR for tracking and discussion at this point in time.

Fixes #412.

Todo:
- [x] Base
- [X] Networking
- [X] Steam
- [x] Types
- [x] Util

### CODE REVIEW

File: SteamKit2/SteamKit2/Steam/WebAPI/WebAPI.cs [hunk 1]
```diff
@@ -443,6 +449,16 @@ public override bool TryInvokeMember( InvokeMemberBinder binder, object[] args,
         /// <returns>A dynamic <see cref="Interface"/> object to interact with the Web API.</returns>
         public static Interface GetInterface( Uri baseAddress, string iface, string apiKey = "" )
         {
+            if ( baseAddress == null )
```
Comment (xPaw) [inline SteamKit2/SteamKit2/Steam/WebAPI/WebAPI.cs]: Shouldn't these be done in `AsyncInterface` constructor instead?

File: SteamKit2/SteamKit2/Types/Manifest.cs [hunk 2]
```diff
@@ -115,6 +115,11 @@ private Steam3Manifest()
 
         public Steam3Manifest(byte[] data)
         {
+            if (data ==  null)
```
Comment (xPaw) [inline SteamKit2/SteamKit2/Types/Manifest.cs]: spacing

File: SteamKit2/SteamKit2/Steam/WebAPI/WebAPI.cs (hunk 1 above)
Comment (yaakov-h) [reply SteamKit2/SteamKit2/Steam/WebAPI/WebAPI.cs]: Could be, but then param names could get out of sync.
